// TEMPORARY: mock snapshot for /preview/context. Delete with the route.
import type { ContextTreeNode, ContextTreeSnapshot, ContextTreeUpdate } from "@first-tree/shared";

const node = (
  id: string,
  parentId: string | null,
  path: string,
  title: string,
  kind: "root" | "domain" | "subdomain" | "leaf",
  changeType: ContextTreeNode["changeType"],
): ContextTreeNode => ({
  id,
  parentId,
  path,
  sourcePath: kind === "leaf" ? `${path}.md` : null,
  title,
  kind,
  owners: [],
  preview: changeType ? `Mock preview content for **${title}**.` : null,
  relatedNodeIds: [] as string[],
  affectedContextArea: title,
  changeType,
  changedAtCommit: changeType ? "83c3939" : null,
});

const update = (
  id: string,
  nodeId: string,
  path: string,
  title: string,
  changeType: ContextTreeUpdate["changeType"],
  changedBy: string,
  area: string,
  owners: string[] = [],
): ContextTreeUpdate => ({
  id,
  nodeId,
  path,
  title,
  changeType,
  affectedContextArea: area,
  reason: "Recent commit",
  summary: `${changedBy} ${changeType} ${title}: clarified scope and refreshed examples.`,
  changedBy,
  owners,
  relatedNodeIds: [],
  sourceCommit: "83c3939e",
  riskLevel: "low",
});

export const MOCK_CONTEXT_SNAPSHOT: ContextTreeSnapshot = {
  // A real binding is always a full URL (validated by contextTreeRepoSchema);
  // the preview uses one so source links resolve the way they do in production.
  repo: "https://github.com/agent-team-foundation/first-tree-context",
  branch: "main",
  // Full 40-hex SHA: source links are exact-commit by contract and the
  // builder rejects short SHAs, so the preview must cite one the way a real
  // binding does.
  headCommit: "83c3939e90b1a2b3c4d5e6f708192a3b4c5d6e7f",
  syncedAt: new Date().toISOString(),
  snapshotStatus: "active",
  contextStatus: {
    label: "Context Tree is up to date",
    detail: "Agents have a synced team context snapshot available.",
    severity: "ok",
  },
  summary: { addedCount: 1, editedCount: 4, removedCount: 1, changedNodeCount: 6 },
  usage: {
    windowDays: 7,
    agentCount: 4,
    usageCount: 18,
    recentEvents: [
      {
        id: "evt-1",
        agentId: "agent-coder",
        agentName: "gandy-coder",
        agentAvatarColorToken: "hue-1",
        chatId: "chat-design-spike",
        chatTitle: "design-spike",
        nodePath: "members/Gandy2025/designs/context-tree-usage-signal.md",
        viewerCanAccess: true,
        createdAt: new Date(Date.now() - 2 * 60_000).toISOString(),
      },
      {
        id: "evt-2",
        agentId: "agent-reviewer",
        agentName: "reviewer",
        agentAvatarColorToken: "hue-4",
        chatId: "chat-onboarding-q3",
        chatTitle: "onboarding-q3",
        nodePath: "domains/onboarding/NODE.md",
        viewerCanAccess: true,
        createdAt: new Date(Date.now() - 12 * 60_000).toISOString(),
      },
      {
        id: "evt-3",
        agentId: "agent-qa",
        agentName: "qa-bot",
        agentAvatarColorToken: "hue-2",
        chatId: "chat-qa-run-42",
        chatTitle: "qa-run-42",
        nodePath: "domains/quality/NODE.md",
        viewerCanAccess: true,
        createdAt: new Date(Date.now() - 60 * 60_000).toISOString(),
      },
      {
        id: "evt-4",
        agentId: "agent-coder",
        agentName: "gandy-coder",
        agentAvatarColorToken: "hue-1",
        chatId: "chat-weekly-retro",
        chatTitle: "weekly-retro",
        nodePath: "NODE.md",
        viewerCanAccess: true,
        createdAt: new Date(Date.now() - 4 * 60 * 60_000).toISOString(),
      },
      {
        id: "evt-5",
        agentId: "agent-internal",
        agentName: "internal-agent",
        // No manager-set color → web falls back to a deterministic hash
        // of agentId via resolveAvatarHue.
        agentAvatarColorToken: null,
        chatId: "chat-internal-review",
        chatTitle: "internal-review",
        // Pre-P0 event — no node path recorded; the feed falls back to
        // "read the context tree".
        nodePath: null,
        // Caller is not a member of this chat — the label shows but renders as
        // inert text (no deep link), exercising the non-clickable preview path.
        viewerCanAccess: false,
        createdAt: new Date(Date.now() - 6 * 60 * 60_000).toISOString(),
      },
    ],
  },
  io: {
    windowDays: 7,
    summary: {
      read: { agentCount: 4, eventCount: 18, targetCount: 12 },
      write: { agentCount: 2, eventCount: 5, targetCount: 5 },
    },
    agents: [
      {
        agentId: "agent-coder",
        agentName: "gandy-coder",
        agentAvatarColorToken: "hue-1",
        runtimeProvider: "claude-code",
        readCount: 9,
        writeCount: 3,
        lastReadAt: new Date(Date.now() - 2 * 60_000).toISOString(),
        lastWriteAt: new Date(Date.now() - 30 * 60_000).toISOString(),
      },
      {
        agentId: "agent-reviewer",
        agentName: "reviewer",
        agentAvatarColorToken: "hue-4",
        runtimeProvider: "claude-code",
        readCount: 4,
        writeCount: 0,
        lastReadAt: new Date(Date.now() - 12 * 60_000).toISOString(),
        lastWriteAt: null,
      },
      {
        agentId: "agent-qa",
        agentName: "qa-bot",
        agentAvatarColorToken: "hue-2",
        runtimeProvider: "codex",
        readCount: 0,
        writeCount: 2,
        lastReadAt: null,
        lastWriteAt: new Date(Date.now() - 60 * 60_000).toISOString(),
      },
    ],
    recentEvents: [
      {
        id: "io-1",
        agentId: "agent-coder",
        agentName: "gandy-coder",
        agentAvatarColorToken: "hue-1",
        runtimeProvider: "claude-code",
        action: "read",
        source: "legacy_context_tree_usage",
        targetKind: "file",
        targetPath: "members/Gandy2025/designs/context-tree-usage-signal.md",
        chatId: "chat-design-spike",
        chatTitle: "design-spike",
        viewerCanAccess: true,
        createdAt: new Date(Date.now() - 2 * 60_000).toISOString(),
      },
      {
        id: "io-2",
        agentId: "agent-qa",
        agentName: "qa-bot",
        agentAvatarColorToken: "hue-2",
        runtimeProvider: "codex",
        action: "read",
        source: "shell_command",
        targetKind: "file",
        targetPath: "domains/quality/NODE.md",
        chatId: "chat-qa-run-42",
        chatTitle: "qa-run-42",
        viewerCanAccess: true,
        createdAt: new Date(Date.now() - 60 * 60_000).toISOString(),
      },
      {
        id: "io-3",
        agentId: "agent-reviewer",
        agentName: "reviewer",
        agentAvatarColorToken: "hue-4",
        runtimeProvider: "claude-code",
        action: "read",
        source: "legacy_context_tree_usage",
        targetKind: "file",
        targetPath: "domains/onboarding/NODE.md",
        chatId: "chat-onboarding-q3",
        chatTitle: "onboarding-q3",
        viewerCanAccess: true,
        createdAt: new Date(Date.now() - 12 * 60_000).toISOString(),
      },
    ],
    writes: [
      // Agent-attributed write (telemetry reconciled the git author to an
      // agent) carrying its PR + a medium risk on a domain-level node.
      {
        id: `${"a".repeat(40)}:system/cloud/team/tenancy-and-identity.md`,
        nodeId: "file:system/cloud/team/tenancy-and-identity",
        nodePath: "system/cloud/team/tenancy-and-identity",
        title: "Tenancy And Identity",
        changeType: "edited",
        summary: "record team deletion semantics",
        riskLevel: "medium",
        authorName: "gandy-coder",
        agentId: "agent-coder",
        agentName: "gandy-coder",
        agentAvatarColorToken: "hue-1",
        commit: "a".repeat(40),
        prNumber: 514,
        createdAt: new Date(Date.now() - 48 * 60_000).toISOString(),
      },
      // Added leaf, reconciled to a reviewer agent, no PR (committed directly).
      {
        id: `${"c".repeat(40)}:members/yzw/notebook.md`,
        nodeId: "file:members/yzw/notebook",
        nodePath: "members/yzw/notebook",
        title: "Notebook",
        changeType: "added",
        summary: "seed reviewer notebook",
        riskLevel: "low",
        authorName: "reviewer",
        agentId: "agent-reviewer",
        agentName: "reviewer",
        agentAvatarColorToken: "hue-4",
        commit: "c".repeat(40),
        prNumber: null,
        createdAt: new Date(Date.now() - 90 * 60_000).toISOString(),
      },
      // Root NODE.md edit: node path is "" (the tree root), so the feed must
      // render a friendly label instead of an empty target.
      {
        id: `${"e".repeat(40)}:NODE.md`,
        nodeId: "root",
        nodePath: "",
        title: "Context Tree",
        changeType: "edited",
        summary: "refresh the root index",
        riskLevel: "medium",
        authorName: "gandy-coder",
        agentId: "agent-coder",
        agentName: "gandy-coder",
        agentAvatarColorToken: "hue-1",
        commit: "e".repeat(40),
        prNumber: 803,
        createdAt: new Date(Date.now() - 20 * 60_000).toISOString(),
      },
      // Unmatched git author (a PR-merge commit telemetry never saw): no agent,
      // so we honestly show the git author + PR, and a high-risk removal.
      {
        id: `${"b".repeat(40)}:practices/tree-maintenance.md`,
        nodeId: "removed:practices/tree-maintenance",
        nodePath: "practices/tree-maintenance",
        title: "Tree Maintenance Practices",
        changeType: "removed",
        summary: "retire tree maintenance guidance",
        riskLevel: "high",
        authorName: "yuezengwu",
        agentId: null,
        agentName: null,
        agentAvatarColorToken: null,
        commit: "b".repeat(40),
        prNumber: 702,
        createdAt: new Date(Date.now() - 3 * 60 * 60_000).toISOString(),
      },
    ],
    writesTotal: 4,
    skipped: { windowDays: 7, totalEventCount: 0, reasons: [] },
  },
  nodes: [
    node("root", null, "/", "Context Tree", "root", null),

    // AGENTS: quiet branch with 3 quiet L2 children.
    node("agents", "root", "/agents", "AGENTS", "domain", null),
    node("agents/msg", "agents", "/agents/msg", "Messaging System", "subdomain", null),
    node("agents/prod", "agents", "/agents/prod", "Product Direction", "subdomain", null),
    node("agents/wc", "agents", "/agents/wc", "Web Console — Workspace", "subdomain", null),

    // First Tree Skill CLI: quiet branch with 5 quiet L2 children.
    node("ftskill", "root", "/ftskill", "First Tree Skill CLI", "domain", null),
    node("ftskill/build", "ftskill", "/ftskill/build", "Build And Distribution", "subdomain", null),
    node("ftskill/cred", "ftskill", "/ftskill/cred", "Credential-Free Core Onboarding", "subdomain", null),
    node("ftskill/onb", "ftskill", "/ftskill/onb", "Onboarding", "subdomain", null),
    node("ftskill/repo", "ftskill", "/ftskill/repo", "Repo Architecture", "subdomain", null),
    node("ftskill/src", "ftskill", "/ftskill/src", "Source/Workspace Installation Contract", "subdomain", null),

    // Nova: 1 own edit, 1 hidden quiet child.
    node("nova", "root", "/nova", "Nova", "domain", "edited"),
    node("nova/legacy", "nova", "/nova/legacy", "Legacy CLI Notes", "subdomain", null),

    // Members: 4 updates including selected Notebook.
    node("members", "root", "/members", "Members", "domain", "edited"),
    node("members/yzw", "members", "/members/yzw", "yuezengwu", "subdomain", "edited"),
    node("members/yzw/notebook", "members/yzw", "/members/yzw/notebook", "Notebook", "leaf", "added"),
    node("members/yzw/journal", "members/yzw", "/members/yzw/journal", "Journal", "leaf", null),
    node("members/yzw/scratch", "members/yzw", "/members/yzw/scratch", "Scratch", "leaf", null),
    node("members/bxh", "members", "/members/bxh", "baixiaohang", "subdomain", null),
    node("members/lc", "members", "/members/lc", "liuchao", "subdomain", null),

    // Practices: Tree Maintenance has its own removed change, plus 1 hidden quiet child.
    node("practices", "root", "/practices", "Practices", "domain", "edited"),
    node("practices/tm", "practices", "/practices/tm", "Tree Maintenance", "subdomain", "removed"),
    node("practices/cr", "practices", "/practices/cr", "Code Review", "subdomain", null),
  ],
  influence: {
    windowDays: 7,
    // Fewer decisions than reads on purpose: most reads are navigation, and the
    // preview should not suggest the two numbers track each other.
    decisionCount: 5,
    effects: { conflicted: 1, redirected: 1, constrained: 2, confirmed: 1 },
    nodes: [
      {
        nodePath: "members/yzw/notebook.md",
        decisionCount: 3,
      },
      {
        nodePath: "members/yzw/journal.md",
        decisionCount: 2,
      },
    ],
    recentEvents: [
      {
        id: "influence-1",
        agentId: "agent-coder",
        agentName: "gandy-coder",
        agentAvatarColorToken: "hue-1",
        effect: "conflicted",
        summary: "The fixed release date and the pre-release security audit rule cannot both hold.",
        evidence: [
          {
            repoUrl: "https://github.com/acme/first-tree-context",
            commit: "0123456789abcdef0123456789abcdef01234567",
            nodePath: "members/yzw/journal.md",
            heading: "Release safety gates",
          },
        ],
        chatId: "chat-design-spike",
        chatTitle: "design-spike",
        createdAt: new Date(Date.now() - 4 * 60_000).toISOString(),
      },
      {
        id: "influence-2",
        agentId: "agent-reviewer",
        agentName: "reviewer",
        agentAvatarColorToken: "hue-4",
        effect: "constrained",
        summary: "The organization-isolation rule ruled out a global shared index.",
        evidence: [
          {
            repoUrl: "https://github.com/acme/first-tree-context",
            commit: "0123456789abcdef0123456789abcdef01234567",
            nodePath: "members/yzw/notebook.md",
            heading: "Organization isolation",
          },
        ],
        chatId: "chat-resource-layer",
        chatTitle: "resource-layer",
        createdAt: new Date(Date.now() - 26 * 60_000).toISOString(),
      },
    ],
  },
  edges: [],
  changes: [],
  updates: [
    update(
      "u1",
      "members/yzw/notebook",
      "/members/yzw/notebook",
      "Notebook",
      "added",
      "yuezengwu",
      "members / yuezengwu / notebook",
      ["yuezengwu"],
    ),
    update("u2", "members/yzw", "/members/yzw", "yuezengwu", "edited", "yuezengwu", "members / yuezengwu", [
      "yuezengwu",
    ]),
    update("u3", "members", "/members", "Members", "edited", "yuezengwu", "members", []),
    update("u4", "nova", "/nova", "Nova", "edited", "yuezengwu", "nova", ["liuchao-001", "yuezengwu"]),
    update(
      "u5",
      "practices/tm",
      "/practices/tm",
      "Tree Maintenance Practices",
      "removed",
      "yuezengwu",
      "practices / tree maintenance",
      [],
    ),
    update("u6", "practices", "/practices", "Practices", "edited", "baixiaohang", "practices", [
      "liuchao-001",
      "bingran-you",
    ]),
  ],
};
