import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";

/**
 * Lock the Claude Agent SDK option shape the handler passes to `query()`.
 *
 * `settingSources: ["user", "project"]` is the single knob that drives two
 * separate behaviors:
 *   - `"project"` — loads the workspace CLAUDE.md generated by bootstrap,
 *     which carries the agent's identity + First Tree SDK reference.
 *   - `"user"` — inherits the operator's local ~/.claude/settings.json so
 *     their thinking mode, effortLevel, plugins, skills, hooks, statusLine,
 *     and MCP servers carry over. Server-managed fields (model, systemPrompt,
 *     env, permissionMode) still win because they ride as explicit options.
 *
 * Dropping either entry silently breaks one of those two contracts with no
 * runtime error — exactly the shape of regression we hit when this array
 * was `["project"]` only (user-level "model": "opus" stopped inheriting
 * and agents silently fell back to Sonnet). This test pins both entries.
 */

const capturedCalls: Array<{ options?: Record<string, unknown> }> = [];

vi.mock("@anthropic-ai/claude-agent-sdk", () => {
  const fakeQuery = {
    [Symbol.asyncIterator]() {
      return {
        next: async () => ({ done: true, value: undefined }),
      };
    },
    close: () => {},
    setModel: async () => {},
  };
  return {
    query: (args: { options?: Record<string, unknown> }) => {
      capturedCalls.push({ options: args?.options });
      return fakeQuery;
    },
  };
});

vi.mock("../../../runtime/agent-briefing.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../../runtime/agent-briefing.js")>();
  return {
    ...actual,
    buildAgentBriefing: vi.fn(actual.buildAgentBriefing),
  };
});

import { mockCtxPlumbing } from "../../../__tests__/test-helpers.js";
import { buildAgentBriefing } from "../../../runtime/agent-briefing.js";
import { createAgentConfigCache } from "../../../runtime/agent-config-cache.js";
import type { SessionContext } from "../../../runtime/handler.js";
import { noopDeliveryToken } from "../../../runtime/handler.js";
import { createClaudeCodeHandler } from "../index.js";

const AGENT_ID = "019d9a97-90b0-716b-8317-a8c0be8430d7";

let workspaceRoot: string;

beforeAll(() => {
  workspaceRoot = mkdtempSync(join(tmpdir(), "ftt-sdk-options-"));
});

afterAll(() => {
  rmSync(workspaceRoot, { recursive: true, force: true });
});

afterEach(() => {
  vi.unstubAllEnvs();
});

function buildCache(env: Array<{ key: string; value: string; sensitive: boolean }> = []) {
  const stubSdk = {
    fetchAgentConfig: async () => ({
      agentId: AGENT_ID,
      version: 1,
      payload: { prompt: { append: "" }, model: "", mcpServers: [], env, gitRepos: [] },
      updatedAt: new Date().toISOString(),
      updatedBy: "test",
    }),
  } as unknown as Parameters<typeof createAgentConfigCache>[0]["sdk"];
  return createAgentConfigCache({ sdk: stubSdk });
}

function buildSessionCtx(chatId: string, buildAgentEnv?: SessionContext["buildAgentEnv"]): SessionContext {
  const sendMessage = async () => undefined;
  const plumbing = mockCtxPlumbing({ sendMessage }, chatId);
  return {
    agent: {
      agentId: AGENT_ID,
      inboxId: "inbox-test",
      displayName: "test",
      type: "agent",
      visibility: "organization",
      delegateMention: null,
      metadata: {},
    },
    sdk: { serverUrl: "http://test", sendMessage } as unknown as SessionContext["sdk"],
    chatId,
    log: () => {},
    recordProviderActivity: () => {},
    noteTurnStart: () => {},
    emitEvent: () => {},
    ...plumbing,
    ...(buildAgentEnv ? { buildAgentEnv } : {}),
  };
}

describe("claude-code handler — SDK options", () => {
  it("passes settingSources=['user','project'] to claudeQuery", async () => {
    capturedCalls.length = 0;

    const cache = buildCache();
    await cache.refresh(AGENT_ID);

    const handler = createClaudeCodeHandler({
      runtimeProvider: "claude-code",
      workspaceRoot,
      agentName: "test-agent",
      agentConfigCache: cache,
    });
    const ctx = buildSessionCtx("chat-settings");
    await handler.start(
      { id: "msg-1", chatId: "chat-settings", senderId: "user", format: "text", content: "hi", metadata: null },
      ctx,
      noopDeliveryToken(),
    );

    expect(capturedCalls).toHaveLength(1);
    const options = capturedCalls[0]?.options;
    expect(options?.settingSources).toEqual(["user", "project"]);

    await handler.shutdown();
  });

  it("sets bypassPermissions + allowDangerouslySkipPermissions so user permission lists cannot gate the agent", async () => {
    capturedCalls.length = 0;

    const cache = buildCache();
    await cache.refresh(AGENT_ID);

    const handler = createClaudeCodeHandler({
      runtimeProvider: "claude-code",
      workspaceRoot,
      agentName: "test-agent",
      agentConfigCache: cache,
    });
    const ctx = buildSessionCtx("chat-perm");
    await handler.start(
      { id: "msg-2", chatId: "chat-perm", senderId: "user", format: "text", content: "hi", metadata: null },
      ctx,
      noopDeliveryToken(),
    );

    const options = capturedCalls[0]?.options;
    expect(options?.permissionMode).toBe("bypassPermissions");
    expect(options?.allowDangerouslySkipPermissions).toBe(true);

    await handler.shutdown();
  });

  it("disables AskUserQuestion via the SDK disallowedTools list", async () => {
    capturedCalls.length = 0;

    const cache = buildCache();
    await cache.refresh(AGENT_ID);

    const handler = createClaudeCodeHandler({
      runtimeProvider: "claude-code",
      workspaceRoot,
      agentName: "test-agent",
      agentConfigCache: cache,
    });
    const ctx = buildSessionCtx("chat-disallow");
    await handler.start(
      { id: "msg-3", chatId: "chat-disallow", senderId: "user", format: "text", content: "hi", metadata: null },
      ctx,
      noopDeliveryToken(),
    );

    const options = capturedCalls[0]?.options;
    // AskUserQuestion is not supported in First Tree — it is disabled at the
    // SDK level via disallowedTools rather than bridged through canUseTool.
    expect(options?.disallowedTools).toContain("AskUserQuestion");
    expect(options?.canUseTool).toBeUndefined();

    await handler.shutdown();
  });

  it.runIf(process.platform !== "win32")(
    "uses the payload-overridden final child PATH for provider CLI detection",
    async () => {
      capturedCalls.length = 0;
      vi.mocked(buildAgentBriefing).mockClear();

      const daemonBin = join(workspaceRoot, "daemon-bin");
      const payloadBin = join(workspaceRoot, "payload-bin");
      const finalProviderBin = join(workspaceRoot, "final-provider-bin");
      mkdirSync(daemonBin, { recursive: true });
      mkdirSync(payloadBin, { recursive: true });
      mkdirSync(finalProviderBin, { recursive: true });
      writeFileSync(join(daemonBin, "gh"), "#!/bin/sh\n", { mode: 0o755 });
      writeFileSync(join(payloadBin, "gh"), "#!/bin/sh\n", { mode: 0o755 });
      writeFileSync(join(finalProviderBin, "glab"), "#!/bin/sh\n", { mode: 0o755 });
      vi.stubEnv("PATH", daemonBin);

      const cache = buildCache([{ key: "PATH", value: payloadBin, sensitive: false }]);
      await cache.refresh(AGENT_ID);

      const handler = createClaudeCodeHandler({
        runtimeProvider: "claude-code",
        workspaceRoot,
        agentName: "test-agent",
        agentConfigCache: cache,
      });
      const buildAgentEnv = vi.fn((env: NodeJS.ProcessEnv) => ({ ...env, PATH: finalProviderBin }));
      const ctx = buildSessionCtx("chat-provider-path", buildAgentEnv);
      await handler.start(
        {
          id: "msg-provider-path",
          chatId: "chat-provider-path",
          senderId: "user",
          format: "text",
          content: "hi",
          metadata: null,
        },
        ctx,
        noopDeliveryToken(),
      );

      const childEnv = capturedCalls[0]?.options?.env;
      expect(buildAgentEnv).toHaveBeenCalledWith(expect.objectContaining({ PATH: payloadBin }));
      expect(childEnv).toMatchObject({ PATH: finalProviderBin });

      const briefing = vi.mocked(buildAgentBriefing).mock.results[0]?.value;
      expect(briefing).not.toContain("final provider `PATH`");
      expect(briefing).not.toContain("detected `glab`");

      await handler.shutdown();
    },
  );
});
