// Core functions — programmatic API for external CLI consumers

// SDK — re-export for convenience
export type { AccessTokenProvider, RegisterResult, SdkConfig } from "@first-tree/client";
export { FirstTreeHubSDK, FirstTreeHubSDK as FirstTreeSDK, SdkError } from "@first-tree/client";
// Connect-token helpers — derive the server URL from a short code fallback or
// legacy JWT.
// `decodeJwtPayload` is intentionally NOT re-exported: it's an internal
// helper used by the CLI account-switch prompt, and its only legitimate
// public use case (URL derivation) already has a dedicated export.
export { deriveHubUrlFromToken, HubUrlDerivationError } from "./commands/_shared/connect-token.js";
// Core types
export type {
  ActivateContextTreeReadInput,
  CheckResult,
  ContextReviewConfigReader,
  ContextReviewConfigResult,
  ContextTreeBindingInput,
  ContextTreeConfigWriter,
  ContextTreeConnectFailure,
  ContextTreeForgeCoordinate,
  ContextTreeForgeRunner,
  ContextTreeReadActivation,
  ContextTreeReadActivationErrorCode,
  ContextTreeReadAuthorityReader,
  ContextTreeReadGitRunner,
  ContextTreeReadSnapshotIdentity,
  ContextTreeReadStage,
  ContextTreeSeedAuthorityReader,
  ContextTreeSeedPreflight,
  ContextTreeSeedPreflightCliErrorCode,
  ContextTreeSeedStage,
  ContextTreeSetupReport,
  ContextTreeUpdateFailedCategory,
  ContextTreeWriteAuthorityReader,
  ContextTreeWritePreflight,
  ContextTreeWritePreflightCliErrorCode,
  ContextTreeWriteStage,
  LocalContextBinding,
  LocalContextDataLoss,
  LocalContextIntent,
  LocalContextResolveResult,
  LocalContextScaffold,
  LocalContextTreeStats,
  MemberContextReviewConfigReader,
  MemberOrganizationProfile,
  MemberOrganizationResolutionCode,
  MigrationDetection,
  MigrationResult,
  PreflightContextTreeSeedInput,
  PreflightContextTreeWriteInput,
  ResolveLocalContextDeps,
  ResolveLocalContextOptions,
  ServiceInfo,
  ServiceOpResult,
  ServiceState,
  SetContextTreeBindingOptions,
  WorkspaceBoundSource,
  WorkspaceChatExactListItem,
  WorkspaceChatExactListResponse,
  WorkspaceStatus,
  WorkspaceUnboundSibling,
} from "./core/index.js";
export {
  AuthRefreshFailedError,
  AuthRefreshRateLimitedError,
  activateContextTreeRead,
  adoptContextTreeRemote,
  assertLocalContextAgentName,
  blank,
  ClientRuntime,
  ContextTreeReadActivationError,
  ContextTreeSeedPreflightCliError,
  ContextTreeUpdateFailedError,
  ContextTreeWritePreflightCliError,
  checkAgentConfigs,
  checkClientConfig,
  checkNodeVersion,
  checkServerReachable,
  checkWebSocket,
  classifyContextTreeUpdateError,
  computeWorkspaceStatus,
  createContextTreeRemote,
  detectMigrationState,
  discoverWorkspaceRoot,
  ensureContextTreeSkills,
  ensureFreshAccessToken,
  ensureFreshAdminToken,
  formatCheckReport,
  formatContextTreeSetupReport,
  getClientServiceStatus,
  getWorkspaceChatExactForAgent,
  handleClientOrgMismatch,
  InvalidContextTreeBindingInputError,
  InvalidContextTreeReadSnapshotError,
  inspectLocalContextTree,
  installClientService,
  isInteractive,
  isServiceSupported,
  listLocalContextDataLoss,
  listWorkspaceChatsForAgent,
  localContextDataLossForAgent,
  MemberOrganizationResolutionError,
  migrateWorkspaceToW1,
  onboardCheck,
  onboardCreate,
  pickImmediateWorkspaceSources,
  preflightContextTreeSeed,
  preflightContextTreeWrite,
  printResults,
  promoteToWorkspace,
  promptAddAgent,
  promptMissingFields,
  readContextReviewConfig,
  readContextTreeReadSnapshotIdentity,
  readMemberContextReviewConfig,
  readWorkspaceManifest,
  resolveAccessToken,
  resolveCliInvocation,
  resolveContextTreeForgeCoordinate,
  resolveLocalContext,
  resolveMemberOrganizationId,
  resolveServerUrl,
  restartClientService,
  setAgentContextTreeBinding,
  slugFromFilename,
  startClientService,
  status,
  stopClientService,
  titleFromMarkdown,
  uninstallClientService,
  validateContextTreeBindingInput,
  verifyContextTreeForgeAuth,
  writeWorkspaceManifest,
} from "./core/index.js";
